/**
 * Embedding Utilities
 *
 * Helper functions for working with semantic embeddings.
 *
 * IMPORTANT: Embeddings are generated by a dedicated embeddings service or external workers.
 * This module provides utilities for manipulating embeddings, plus a client to request
 * embeddings from the service when needed (e.g., classifier values).
 */

import type { Env } from '../index';
import logger from '../utils/logger';

const EMBEDDING_DIMENSIONS = 768;
// Must match @lobu/embeddings DEFAULT_MODEL_NAME (the local pipeline + service
// fall back to this when EMBEDDINGS_MODEL is unset).
export const DEFAULT_EMBEDDING_MODEL = 'Xenova/bge-base-en-v1.5';
// Allowlist mirroring the embeddings service's MODEL_NAME_PATTERN. Used to
// reject anything unsafe before inlining the configured model into SQL.
const MODEL_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/:-]{0,127}$/;

/**
 * The embedding model this deployment is configured to produce/consume. Every
 * freshly-written event_embeddings row is stamped with this, and similarity
 * queries scope to it so a same-dimension model swap can't compare vectors
 * across incompatible spaces. Reads the same env var (with the same default)
 * as the worker and the embeddings service.
 */
export function getConfiguredEmbeddingModel(): string {
  return process.env.EMBEDDINGS_MODEL || DEFAULT_EMBEDDING_MODEL;
}

/**
 * Resolve the embedding model an operation should read/write, given an optional
 * caller-supplied override. Falls back to the deployment's configured model, so
 * every existing call site keeps its current semantics by passing nothing.
 *
 * A non-default model is only meaningful where vectors under it actually exist
 * — `event_embeddings` is keyed `(event_id, embedding_model, chunk_index)`, so
 * two models coexist in storage, but a model with no rows reads as "nothing is
 * embedded" rather than as an error. Callers that expose this to an agent should
 * surface that emptiness (see `manage_classifiers`' `not_embedded` skip reason)
 * instead of reporting a silent zero-result.
 *
 * Validated here rather than at each call site: the override reaches SQL as an
 * inlined literal via `embeddingModelSqlLiteral`, and one unvalidated path is
 * all it takes.
 */
export function resolveEmbeddingModel(requested?: string | null): string {
  const model = requested?.trim() || getConfiguredEmbeddingModel();
  if (!MODEL_NAME_PATTERN.test(model)) {
    throw new Error(
      `Embedding model '${model}' is not a valid model identifier (allowed: ${MODEL_NAME_PATTERN}).`
    );
  }
  return model;
}

/**
 * SQL-safe string literal for an embedding model, for inlining into a query
 * builder where threading another bound parameter would be error-prone. Always
 * route the value through `resolveEmbeddingModel` first — this re-validates
 * rather than trusting the caller, because an unvalidated model string inlined
 * here is a straight injection.
 */
export function embeddingModelSqlLiteral(model: string): string {
  return `'${resolveEmbeddingModel(model)}'`;
}

/**
 * SQL predicate: does the event aliased `eventAlias` need (re)embedding under
 * `model`? True when it has no representative (chunk 0) vector for that model —
 * covering "never embedded", a stale model, and a NULL stamp. Centralized so the
 * backfill discovery and the worker fetch can never disagree on what "stale"
 * means. Correlates on `eventAlias`.
 *
 * The model is an explicit argument, not a global read: discovery and the worker
 * fetch MUST agree on which space they are filling, and defaulting it here would
 * let those two sites silently diverge the moment one of them is given an
 * override and the other is not.
 *
 * Expand phase: chunking is not enabled yet (one row per event), so this is the
 * chunk-0 existence check only. The CONTRACT release adds the "long content but
 * no tail chunks" arm once the worker actually produces tail chunks — adding it
 * now would re-queue long events forever (they'd never get a chunk >= 1).
 */
export function needsEmbeddingSql(eventAlias: string, model: string): string {
  const literal = embeddingModelSqlLiteral(model);
  const e = eventAlias;
  return `NOT EXISTS (SELECT 1 FROM event_embeddings emb
    WHERE emb.event_id = ${e}.id AND emb.embedding_model = ${literal} AND emb.chunk_index = 0)`;
}

const DEFAULT_TIMEOUT_MS = 30000;

function resolveEmbeddingServiceUrl(env: Env): string {
  const url = env.EMBEDDINGS_SERVICE_URL?.trim();
  if (!url) {
    throw new Error(
      'EMBEDDINGS_SERVICE_URL is required to generate embeddings. ' +
        'Configure the embeddings service or provide embeddings directly.'
    );
  }
  return url.replace(/\/+$/, '');
}

/**
 * Validate that the embeddings service is reachable and healthy.
 * Call this before attempting to generate embeddings to fail fast with a clear error.
 *
 * @throws Error if service is unavailable or unhealthy
 */
export async function validateEmbeddingsService(env: Env): Promise<void> {
  const url = resolveEmbeddingServiceUrl(env);

  try {
    const response = await fetch(`${url}/health`, {
      method: 'GET',
      signal: AbortSignal.timeout(5000),
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => '');
      throw new Error(
        `Embeddings service unhealthy (${response.status}): ${errorText.slice(0, 200)}`
      );
    }

    const health = (await response.json()) as { ok?: boolean };
    if (!health.ok) {
      throw new Error('Embeddings service returned unhealthy status');
    }

    logger.debug({ url }, '[Embeddings] Service health check passed');
  } catch (error) {
    if (error instanceof Error && error.message.includes('unhealthy')) {
      throw error;
    }
    throw new Error(
      `Embeddings service unavailable at ${url}. ` +
        'Cannot save automation window without generating embeddings. ' +
        'Start the embeddings service or provide embeddings in extracted_data. ' +
        `Original error: ${error instanceof Error ? error.message : 'Unknown'}`
    );
  }
}

/**
 * Generate embeddings for multiple texts via the embeddings service.
 *
 * @param texts - Array of texts to embed
 * @param env - Environment with embeddings service configuration
 * @param model - Model to embed under; defaults to the deployment's configured model
 * @returns Array of 768-dimensional embedding vectors
 */
export async function generateEmbeddings(
  texts: string[],
  env: Env,
  model?: string | null
): Promise<number[][]> {
  if (texts.length === 0) {
    return [];
  }

  const requestedModel = resolveEmbeddingModel(model);

  const url = resolveEmbeddingServiceUrl(env);
  const parsedTimeout = Number.parseInt(env.EMBEDDINGS_TIMEOUT_MS || '', 10);
  const timeoutMs = Number.isFinite(parsedTimeout) ? parsedTimeout : DEFAULT_TIMEOUT_MS;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);

  try {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    if (env.EMBEDDINGS_SERVICE_TOKEN) {
      headers.Authorization = `Bearer ${env.EMBEDDINGS_SERVICE_TOKEN}`;
    }

    const response = await fetch(`${url}/api/embeddings`, {
      method: 'POST',
      headers,
      body: JSON.stringify({ texts, model: requestedModel }),
      signal: controller.signal,
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Embeddings service error (${response.status}): ${errorText.slice(0, 300)}`);
    }

    const payload = (await response.json()) as {
      embeddings?: number[][];
      dimensions?: number;
      model?: string;
    };

    if (!Array.isArray(payload.embeddings)) {
      throw new Error('Embeddings service response missing embeddings array');
    }

    if (payload.embeddings.length !== texts.length) {
      throw new Error(
        `Embeddings service returned ${payload.embeddings.length} embeddings for ${texts.length} texts`
      );
    }

    if (payload.dimensions && payload.dimensions !== EMBEDDING_DIMENSIONS) {
      throw new Error(
        `Embeddings service returned ${payload.dimensions} dimensions (expected ${EMBEDDING_DIMENSIONS})`
      );
    }

    const invalidIndex = payload.embeddings.findIndex((embedding) => !isValidEmbedding(embedding));
    if (invalidIndex !== -1) {
      throw new Error(`Embeddings service returned invalid embedding at index ${invalidIndex}`);
    }

    // Version-stamp guard: the query vector we are about to compare against
    // stored rows MUST come from the same model those rows are scoped to. If the
    // service reports a different model, fail loud rather than silently
    // comparing across incompatible vector spaces.
    //
    // Checked against the REQUESTED model, not the configured one. A caller
    // asking for a non-default model is the case this guard most needs to cover:
    // the local backend pins one model per process and ignores an unsupported
    // request, so without this the caller would silently get default-model
    // vectors back and stamp them as the requested model — poisoning the very
    // table the model stamp exists to keep clean.
    if (payload.model) {
      if (payload.model !== requestedModel) {
        throw new Error(
          `Embeddings service returned model '${payload.model}' but '${requestedModel}' was ` +
            `requested. Refusing to compare across incompatible vector spaces — align ` +
            `EMBEDDINGS_MODEL on the server and the embeddings service, or use a service ` +
            `that can serve the requested model.`
        );
      }
      logger.debug({ model: payload.model }, '[Embeddings] Service model');
    }

    return payload.embeddings;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Validate embedding dimensions
 *
 * @param embedding - Embedding to validate
 * @param expectedDimensions - Expected dimensions (default: 768)
 * @returns true if valid, false otherwise
 */
function isValidEmbedding(
  embedding: number[] | null | undefined,
  expectedDimensions: number = EMBEDDING_DIMENSIONS
): embedding is number[] {
  return (
    Array.isArray(embedding) &&
    embedding.length === expectedDimensions &&
    embedding.every((n) => typeof n === 'number' && !Number.isNaN(n))
  );
}
