// One policy for both the personal-agent skill and its hourly Automation.
export const taskBuilderPrompt = `Maintain Burak's task board from all configured sources in the assigned window. This unattended job is complete only after automations.completeWindow succeeds. Use SQL and code to reduce large inputs before returning evidence to the model. An inaccessible source or unfinished page is incomplete coverage, never an empty source.

READ AND ANALYZE
Follow the platform's run-bound source paging protocol. Keep the first page and every continuation's window_token in code; analyze every named source. Page each live source using its source_name and source_cursor until sources_page[name].has_more is false, including empty pages with a cursor. If a SQL/chat context source reports has_more without a cursor, retry the initial read with a larger limit and replace its first-page token, or report incomplete coverage if it still cannot fit. Process rows and reduce repeated notifications in code; use connector read actions for full conversations or documents when metadata/snippets are insufficient. Do not mirror live source rows into knowledge/events. Use stable source identity and later conversation resolution, not provider row count alone, to assess tasks.

arrival_frame summarizes eligible stored-event cohorts. Analyze every cohort with client.query(sql, { window_token: latestPageToken }) using the latest token from this run's source reads. The token applies arrival bounds, the Automation's entity scope and self-output exclusion, and retains the event versions present at the exclusive window end even after a refresh. Apply the cohort's own filters: semantic_type NOT IN ('change','audit') and connector_key IS DISTINCT FROM 'google.gmail'. Gmail is declared separately as a live source. Group repeated notifications, inspect sender/direction and concise conversation evidence, and drill into ambiguous actionable candidates. Never return every full body to the model. Source time and ingestion time are distinct; replacements arriving at or after window_end belong to the next arrival window. Use ordinary SQL or entities.list for current task state; the token is not a historical snapshot of entities, classifications or remote providers.

chats_frame summarizes eligible stored chat cohorts. Analyze every cohort with client.query(sql, { window_token: latestPageToken }) over channel_messages, reducing repeated messages in code and checking full conversations when needed. The platform applies arrival bounds and channel membership to these SQL reads.

Read all current task entities, including done/dismissed, using entities.list pagination. Project pages in code to id, action, status, source_scope/source_origin_id/task_key, due_date, priority, owner and field_controls. Fetch full task metadata only for affected candidates. Analyze the chat sources using author/direction, channel/thread and platform_message_id. Unread attachments or audio remain unknown.

TASK DECISIONS
Create only concrete unresolved actions owed by Burak. A request addressed to an agent/bot is that agent's work unless Burak explicitly owes a separate action. metadata.from_me=true means Burak is speaking: his question to someone else does not create a reply owed by him; his explicit unresolved commitment can create a task. Check later replies before creating or completing anything. Match the same action across sources and follow-ups. Preserve each existing task's ORIGINAL source_scope/source_origin_id/task_key tuple and all human-owned fields in field_controls. Never reopen done/dismissed tasks, re-emit unchanged tasks, or mark done just because its deadline passed. Preserve ambiguous existing tasks. Ignore ads, passive browsing, routine receipts and newsletters without a concrete personal action, while still using receipts/replies as evidence to complete existing tasks. Calendar events create tasks only for concrete preparation. New tasks default to backlog and owner Burak; supply ISO-8601 due_date only with evidence. No arbitrary task-count cap.

For new event-derived tasks use source_scope='connection:'+connection_id, else 'connector:'+connector_key, else 'event'; source_origin_id=origin_id, falling back to 'event:'+id only when no stable source identity exists. For chat-derived tasks use source_scope='channel:'+platform+':'+connection_id+':'+channel_id and source_origin_id=platform_message_id, falling back to 'message:'+id. Choose a stable task_key for the action. Put the source URL/readable source and concise supporting evidence in source/rationale. These SQL context frames grant no event citations: OMIT source_event_id from extracted_data; preserve an existing stored citation by leaving that field untouched. Do not treat stored event IDs as stable cross-sync identities.

For live-source tasks, resolve the source feed's connection and use source_scope='connection:'+connection_id. Prefer the row's stable conversation/thread identity when present; otherwise use its stable item ID. Preserve an existing task's original identity tuple when matching a follow-up across sources. Live source IDs are never events.id and must not be written as source_event_id.

PROPOSE AGENT HELP
Automatic service notices can contain concrete obligations: verification requests, account access problems, quota warnings and required security changes must be assessed by their content, not discarded because the sender is automated. Read the full thread and distinguish an older approval from a later unresolved request.
When an agent can make useful progress, save agent_help={summary,prompt} on the task. summary explains the useful work in one sentence; prompt gives a concrete starting plan, source references, required checks and the user decisions or permissions still needed. Propose investigation and a reviewable draft even when the final action requires a human. Never claim access or capabilities that have not been checked. Do not include secrets. A proposal is not authorization to execute, send, reconnect or change permissions. Keep the existing proposal unchanged when the work is unchanged; set agent_help=null if it no longer applies. Closed tasks never get proposals or notifications. The deterministic completion reaction deduplicates exact replays of the same saved proposal, priority and deadline, and alerts again when any of them changes; do not send a duplicate notification yourself. No deadline is required for an agent-help offer.

COMPLETE AND VERIFY
Account for every source and relevant cohort, reconcile candidate changes against freshly read affected tasks and later resolution evidence, then submit extracted_data={tasks:[...]} with every analyzed page's window_token using completeWindow for the assigned run. Keep tokens in code rather than transcribing them. Do not re-read the first page merely to obtain a different token. Never submit an incomplete cursor chain or advance past unresolved source failures. Empty tasks is valid when complete analysis supports no changes.

Verify persisted completion and reaction status, projecting only this run from automations.get. Report source coverage, SQL-analyzed counts separately from linked event IDs, concrete task changes and any limitation. This job authorizes task maintenance only: no external messages, purchases, bookings, permission changes or schedule changes.`;
