import { afterEach, expect, test } from "bun:test";
import { type ModuleInterface, moduleRegistry } from "@lobu/core";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { assertPortableArtifact } from "../../../../../../scripts/artifact-portability.mjs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { ApiKeyProviderModule } from "../api-key-provider-module.js";
import { getCatalogModel, resolveModelMetadata } from "../model-catalog.js";
import { buildProviderCatalog } from "../provider-catalog.js";
import { collectProviderModelOptions } from "../provider-model-options.js";

const registry = moduleRegistry as unknown as { modules: Map<string, ModuleInterface> };
const original = registry.modules;
afterEach(() => { registry.modules = original; });

test("picker and runtime share Google's metadata through an OpenAI-compatible alias, offline", async () => {
  const module = new ApiKeyProviderModule({
    providerId: "synthetic-google", registryAlias: "google", sdkCompat: "openai",
    providerDisplayName: "Synthetic Google", providerIconUrl: "", envVarName: "SYNTHETIC_KEY",
    apiKeyInstructions: "", apiKeyPlaceholder: "", authProfilesManager: {} as never,
  });
  module.getModelOptions = async () => { throw new Error("Discovery offline"); };
  module.getModelMetadata = async () => { throw new Error("Known model must not use discovery"); };
  registry.modules = new Map();
  moduleRegistry.register(module);
  const modelId = "gemini-2.5-pro";
  expect(buildProviderCatalog()[0]?.models).toContain(modelId);
  const options = await collectProviderModelOptions("synthetic-agent", "synthetic-user");
  expect(options[module.providerId]?.map(option => option.value)).toContain(`${module.providerId}/${modelId}`);
  const metadata = await resolveModelMetadata(module, modelId, "synthetic-agent", {});
  const catalog = getCatalogModel("google", modelId);
  expect(metadata?.contextWindow).toBe(catalog?.contextWindow);
  expect(metadata?.contextWindow).toBeGreaterThan(128000);
  expect(metadata?.input).toContain("image");
  expect(metadata?.reasoning).toBe(true);

  // Account discovery may include private models absent from the public catalog.
  module.getModelOptions = async () => [{ value: `${module.providerId}/private-model`, label: "Private" }];
  expect((await collectProviderModelOptions("synthetic-agent", "synthetic-user"))[module.providerId]).toEqual(
    [{ value: `${module.providerId}/private-model`, label: "Private" }]
  );
});

test("private models use provider metadata or retain the existing dynamic defaults", async () => {
  const module = {
    providerId: "synthetic-private",
    getModelMetadata: async () => ({ contextWindow: 64000, input: ["text"], reasoning: false }),
  } as never;
  expect(await resolveModelMetadata(module, "private-model", "synthetic-agent", {})).toEqual({
    contextWindow: 64000, input: ["text"], reasoning: false, maxTokens: null,
  });
  expect(await resolveModelMetadata({ providerId: "synthetic-missing" } as never, "private-model", "synthetic-agent", {})).toEqual({
    contextWindow: 128000, input: ["text", "image"], maxTokens: null, reasoning: undefined,
  });
});

test("generated and bundled release data carries only portable capability fields", async () => {
  const data = JSON.parse(readFileSync(new URL("../../../generated/models-dev.json", import.meta.url), "utf8"));
  expect(data.revision).toMatch(/^[a-f0-9]{64}$/);
  // Validate generated bytes, including fields inherited from upstream.
  const bundled = await build({
    entryPoints: [fileURLToPath(new URL("../model-catalog.ts", import.meta.url))],
    bundle: true, platform: "node", format: "esm", packages: "external", write: false,
  });
  const directory = mkdtempSync(join(tmpdir(), "lobu-model-catalog-"));
  try {
    writeFileSync(join(directory, "models.json"), JSON.stringify(data));
    writeFileSync(join(directory, "catalog.mjs"), bundled.outputFiles[0]!.text);
    assertPortableArtifact(directory, fileURLToPath(new URL("../../../../../../", import.meta.url)));
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
  for (const provider of Object.values(data.models) as Array<Record<string, object>>) {
    for (const model of Object.values(provider)) {
      expect(Object.keys(model).sort()).toEqual(["contextWindow", "input", "maxTokens", "reasoning", "toolCall"]);
    }
  }
});
